name: test_brew


on:
  push:
    branches:
      - "**"


jobs:
  test:
    name: brew
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1


      - name: Rotate Brew cache
        run: |
          brew update
          brew install awscli 

